// ============================================================
// TRACK TEAM HUB — EDITABLE DATA
// Update the values below to keep your site current.
// ============================================================

const TEAM_PASSWORD = "yinghuatrack26"; // Change this to your team password

const TEAM_NAME = "Yinghua Academy Dragons";
const TEAM_SUBTITLE = "Track & Field";
const TEAM_COLORS = {
  primary: "#790E1D",   // Yinghua maroon
  accent: "#FFD700",    // Yinghua gold
};

// ---- ANNOUNCEMENTS ----
const ANNOUNCEMENTS = [
  {
    date: "2026-04-02",
    title: "Welcome to the 2026 Season!",
    body: "We're excited to kick off another great year of Dragons Track & Field. Bring running shoes, water, and a great attitude to every practice!",
  },
];

// ---- SCHEDULE ----
// type: "practice" or "meet"
// Practices: Tue & Thu 3:30–5:00 PM. Pickup at 5:00 PM from field behind school.
// NOTE: ALL BUS RIDES ARE ONE WAY. Parents must pick up from meet.
const SCHEDULE = [
  // ---- WEEK 1 ----
  { date: "2026-04-02", type: "practice", title: "Practice — Week 1", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM · Gym available",
    plan: {
      sprints: "400m (50-75% pace), 300m (50-75% pace), 200m (75-90%), 2x100m (best effort). Introduce sprint form.",
      distance: "Introduce distance events & basic pacing. Fartlek \"Speed Play\" for 20 min.",
      field: "No field events or hurdles Week 1.",
    }},
  { date: "2026-04-07", type: "practice", title: "Practice — Week 1", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM",
    plan: {
      sprints: "Sprint drills. 4x200m (50-75% pace).",
      distance: "3 min on/steady to 2 min conversational for 20-25 min.",
      field: "Introduce hurdles and long jump.",
    }},
  // ---- NO SCHOOL ----
  { date: "2026-04-09", type: "practice", title: "No School — NO Practice", time: "", location: "Train at home", notes: "" },
  // ---- WEEK 2 ----
  { date: "2026-04-14", type: "practice", title: "Practice — Week 2", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM",
    plan: {
      sprints: "4x300m (50-75% pace).",
      distance: "4x300m (50-75% pace).",
      field: "Practice hurdles and long jump.",
    }},
  { date: "2026-04-16", type: "practice", title: "Pre-Meet Practice — Week 2", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM · Gym available",
    plan: {
      sprints: "Pre-meet: warm-up + 2x200m, 2x100m at 75%.",
      distance: "Pre-meet: 15 min easy running + 3x30 sec striders.",
      field: "Shot put and discus with throws coach.",
    }},
  // ---- WEEK 3 ----
  // (4/18 St. Paul Central was cancelled and rescheduled to 5/9 — see below)
  { date: "2026-04-21", type: "practice", title: "Pre-Meet Practice — Week 3", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM",
    plan: {
      sprints: "Pre-meet: warm-up + 2x200m, 2x100m at 75%.",
      distance: "Pre-meet: 15 min easy running + 3x30 sec striders.",
      field: "Shot put and discus with throws coach.",
    }},
  { date: "2026-04-22", type: "meet", title: "Richfield MS", time: "4:15 PM start · Pickup ~6:00 PM", location: "Richfield HS — 7001 Harriet Ave, Richfield, MN 55423", notes: "Grades 6–8 only (no 5th) · Bus from Yinghua (one-way) · Parents pick up at meet · Jersey to school with uniform bottoms" },
  { date: "2026-04-23", type: "practice", title: "Practice — Week 3", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM · Gym available",
    plan: {
      sprints: "Sprint drills, shuttle relays.",
      distance: "Hills: 10-15x sprint up / recover down. 2x400m (75%).",
      field: "Practice hurdles and long jump.",
    }},
  // ---- WEEK 4 ----
  // NOTE: Throws coach (KP) swapped to Tue 4/28 this week — KP has a work conflict Thu 4/30.
  { date: "2026-04-28", type: "practice", title: "Practice — Week 4", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM",
    plan: {
      sprints: "4x100m relay repeats. Sprint form drills.",
      distance: "Fartlek with pace groups (15 min conversational). 5 min handoff practice.",
      field: "Shot put and discus with throws coach (swapped from Thu this week).",
    }},
  { date: "2026-04-30", type: "practice", title: "Practice — Week 4", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM · Gym available",
    plan: {
      sprints: "400m relay teams (2-3 people; 4x400m each).",
      distance: "400m relay teams (2-3 people; 4x400m each).",
      field: "Practice hurdles and long jump (throws coach out this Thursday).",
    }},
  // ---- WEEK 5 ----
  { date: "2026-05-05", type: "practice", title: "Pre-Meet Practice — Week 5", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM",
    plan: {
      sprints: "Pre-meet: warm-up + 2x200m, 2x100m.",
      distance: "Pre-meet: warm-up + 2 laps + 2 straightaway striders.",
      field: "Practice hurdles, long jump, and relay handoffs.",
    }},
  { date: "2026-05-06", type: "meet", title: "Olson MS–Bloomington", time: "4:15 PM", location: "Jefferson HS — 4001 W 102nd St, Bloomington, MN 55437", notes: "Grades 6-8 · Dismiss 3:05 · Bus 3:15 · Parent pickup ~6:00 PM" },
  { date: "2026-05-07", type: "practice", title: "Practice — Week 5", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM · Gym available",
    plan: {
      sprints: "Sprint drills, shuttle relays.",
      distance: "Fartlek with pace groups (15 min conversational).",
      field: "Shot put and discus with throws coach.",
    }},
  // ---- RESCHEDULED MEET (Saturday, MS only) ----
  { date: "2026-05-09", type: "meet", title: "St. Paul Central H.S. (rescheduled)", time: "9:00 AM", location: "St. Paul Central HS — 275 Lexington Pkwy N, St Paul, MN 55104", notes: "Saturday morning · Grades 5–8 · Parents provide transportation · Done by ~12:00 PM" },
  // ---- WEEK 6 ----
  // NOTE: Week 6 throws swap — KP at practice Tue 5/12, OUT Thu 5/14.
  { date: "2026-05-12", type: "practice", title: "Pre-Meet Practice — Week 6", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM",
    plan: {
      sprints: "Pre-meet: warm-up + 2x200m, 2x100m.",
      distance: "Pre-meet: warm-up + 2 laps + 2 straightaway striders.",
      field: "Shot put and discus with throws coach (swapped from Thu this week).",
    }},
  { date: "2026-05-13", type: "meet", title: "Prior Lake", time: "4:00 PM", location: "Prior Lake HS — 7575 150th St W, Savage, MN 55378", notes: "Grades 6-8 · Dismiss 2:50 · Bus 3:00" },
  { date: "2026-05-14", type: "practice", title: "Pre-Meet Practice — Week 6", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM · Gym available",
    plan: {
      sprints: "Pre-meet: warm-up + 2x200m, 2x100m at 75%.",
      distance: "Pre-meet: 15 min easy running + 3x30 sec striders.",
      field: "Practice hurdles, long jump, and relay handoffs (throws coach out this Thursday).",
    }},
  { date: "2026-05-15", type: "meet", title: "TCGIS", time: "5:00–8:00 PM", location: "Concordia Academy — 2400 Dale St N, Roseville, MN 55113", notes: "Grades 5-8 · No bus · Parents provide transportation" },
  // ---- WEEK 7 ----
  // NOTE: Week 7 — KP at practice Tue 5/19 for throws.
  { date: "2026-05-19", type: "practice", title: "Pre-Meet Practice — Week 7", time: "3:30–5:00 PM", location: "Field behind school", notes: "Pickup at 5:00 PM",
    plan: {
      sprints: "Pre-meet: warm-up + 2x300m, 2x100m.",
      distance: "Pre-meet: warm-up + 2 laps + 2 straightaway striders.",
      field: "Shot put and discus with throws coach.",
    }},
  { date: "2026-05-21", type: "meet", title: "Yinghua In-House Meet & End of Season Party", time: "3:45 PM", location: "Yinghua / NE Park", notes: "Grades 5-8 · Dismiss 3:30" },
];

// ---- MEET INFO ----
// Detailed info for upcoming meets. Keyed by schedule date (YYYY-MM-DD).
// The "This Meet" tab auto-shows the next upcoming meet entry found here.
// signupFormUrl: paste a Google Form URL here to let athletes sign up for events.
// To embed the form directly in the page, use the embeddable share URL (ends in /viewform?embedded=true).
const MEET_INFO = {
  "2026-05-09": {
    title: "St. Paul Central H.S. (rescheduled)",
    date: "2026-05-09",
    dayLabel: "Saturday, May 9",
    location: "St. Paul Central High School Track",
    address: "275 Lexington Pkwy N, St Paul, MN 55104",
    mapUrl: "https://maps.google.com/?q=275+Lexington+Pkwy+N+St+Paul+MN+55104",
    arrival: "9:00 AM start. Plan to be at the track by 8:30 AM for warm-up. Done by ~12:00 PM.",
    transportation: "No bus — parents provide transportation to and from the meet.",
    eligibility: "Grades 5–8.",
    announcements: [
      {
        title: "This is the rescheduled 4/18 meet",
        body: "Trimmed-down format this time — middle school only, shorter distances (60m hurdles and 60m dash), and the whole meet wraps up before noon.",
      },
      {
        title: "Tell a coach which events you want to run",
        body: "Talk to Coach Drew or Coach Lily at Thursday's pre-meet practice (5/7) so we can build heat sheets.",
      },
    ],
    whatToBring: [
      "Yinghua track uniform / team shirt",
      "Running shoes + spikes if you have them",
      "Water bottle (refillable)",
      "Snacks for the morning",
      "Warm layers — early Saturday morning",
    ],
    schedule: [
      { time: "9:00 AM", event: "Opening of Field Events", type: "field" },
      { time: "9:30 AM", event: "4x800m Relay", type: "track" },
      { time: "9:40 AM", event: "60m Hurdles", type: "track" },
      { time: "9:50 AM", event: "60m Dash", type: "track" },
      { time: "10:00 AM", event: "1600m Run", type: "track" },
      { time: "10:20 AM", event: "400m Dash", detail: "No blocks", type: "track" },
      { time: "10:30 AM", event: "800m Run", type: "track" },
      { time: "10:40 AM", event: "200m Run", type: "track" },
      { time: "10:50 AM", event: "1600m Run (fast section)", type: "track" },
      { time: "11:10 AM", event: "4x400m Relay", type: "track" },
      { time: "", event: "4x100m — Anything But a Baton Relay", detail: "Pass anything but a baton!", type: "fun" },
      { time: "", event: "4x100m — Coaches / Parents Relay", detail: "Come cheer on the grown-ups!", type: "fun" },
    ],
  },
  "2026-05-15": {
    title: "TCGIS Muddy Water Relays",
    date: "2026-05-15",
    dayLabel: "Friday, May 15",
    location: "Concordia Academy",
    address: "2400 Dale St N, Roseville, MN 55113",
    mapUrl: "https://maps.google.com/?q=2400+Dale+St+N+Roseville+MN+55113",
    arrival: "Arrive at Concordia by 5:00 PM · Warm-ups + coach/volunteer meeting 5:15 PM · Meet starts 5:45 PM · Team cool-down 8:00 PM · Pickup 8:15 PM.",
    transportation: "No bus — parents provide transportation to and from the meet.",
    eligibility: "Grades 5–8. Boys and girls scored separately.",
    announcements: [
      {
        title: "Almost everything is a relay!",
        body: "Track events are all relays (4 athletes per team) except the Elimination Race. Field events are also team relays — 4 athletes each, 3 attempts apiece, with the best mark per athlete added together for the team's score.",
      },
      {
        title: "Athletes are responsible for arriving on time",
        body: "Track relays will NOT wait for late athletes. Coaches will help remind kids, but athletes need to head to their event right when the previous one starts.",
      },
      {
        title: "Wear the uniform, dress for cool weather",
        body: "Uniform when competing; longer warmup clothing when not. Bring 2-3 full water bottles — it's a 3-hour meet.",
      },
      {
        title: "Schools attending (2026)",
        body: "Agape Christi, Avail Academy, Avalon, Chapel Hill, Christian Heritage, Concordia Academy, DaVinci Academy, Great Oaks, Lake Country, NOVA Classical, Our Lady of Peace, TCGIS, Yinghua.",
      },
    ],
    whatToBring: [
      "Yinghua track uniform / team shirt",
      "2–3 full water bottles",
      "Longer warmup clothing for between events",
      "Running shoes + spikes if you have them",
      "Snacks for a 3-hour evening meet",
    ],
    schedule: [
      { time: "5:00 PM", event: "Athletes arrive at Concordia Academy", type: "note" },
      { time: "5:15 PM", event: "Warm-ups · Volunteer & coach meeting", type: "note" },
      { time: "5:30 PM", event: "Event check-ins begin", type: "note" },
      { time: "5:45 PM", event: "Meet starts — Rolling Schedule", type: "note" },
      { time: "", event: "4x100m Relay", type: "track" },
      { time: "", event: "Distance Medley Relay (1200–400–800–1600)", type: "track" },
      { time: "", event: "Sprint Medley Relay (100–100–200–400)", type: "track" },
      { time: "", event: "4x800m Relay", type: "track" },
      { time: "", event: "4x200m Relay", type: "track" },
      { time: "", event: "Elimination Race", detail: "Distance race — last runner eliminated each 400m until one remains. Lapped runners also out. Only individual event of the meet.", type: "fun" },
      { time: "", event: "4x400m Relay", type: "track" },
      { time: "", event: "Field Event Relays (concurrent)", detail: "4x Shot Put · 4x Discus · 4x Long Jump", type: "field" },
      { time: "8:00 PM", event: "Team cool-down", type: "note" },
      { time: "8:15 PM", event: "Pickup from Concordia Academy", type: "note" },
    ],
    fieldEventNotes: [
      "Field event relays: 4 athletes per team, 3 attempts each. Best mark per athlete added → team score.",
      "Shot Put (6 lb) and Discus (1 kg) are provided by the host. Bring your own relay batons.",
      "If a relay has fewer than 4 athletes, the team can still compete — track relays won't be scored, but field relay marks still add up.",
      "Scoring: 1st = 10 pts, 2nd = 9 pts, ... 10th = 1 pt, 11th+ = 0. Only top 2 relay teams per school score per event.",
      "Max 4 events per athlete (track + field combined).",
    ],
  },
  "2026-05-13": {
    title: "Prior Lake Meet",
    date: "2026-05-13",
    dayLabel: "Wednesday, May 13",
    location: "Prior Lake High School",
    address: "7575 W 150th St, Savage, MN 55378",
    mapUrl: "https://maps.google.com/?q=7575+W+150th+St+Savage+MN+55378",
    arrival: "Meet starts at 4:15 PM (running events, rolling start). Field events begin around 4:00 PM. Bus arrives after 3:15 PM per host's request.",
    transportation: "Bus from Yinghua (one-way only). Dismiss 2:50 · Bus 3:00 · Parents pick up from the meet around 6:00 PM.",
    eligibility: "Grades 6–8 only. Heats run by grade level; sixth graders may compete in 7th-grade events.",
    teams: "Lakeville North · Lakeville South · Northfield · Yinghua Academy",
    announcements: [
      {
        title: "Tell a coach which events you want to run",
        body: "We'll finalize entries at Tuesday's pre-meet practice (5/12). Talk to Coach Drew or Coach Lily about which events you want to do.",
      },
      {
        title: "Teams bring their own throws + batons",
        body: "Yinghua brings our own discus, shot puts, and relay batons. Coaches will have everything at the meet.",
      },
      {
        title: "Stadium etiquette",
        body: "Team camps set up in the stadium bleachers — stay off the infield. No gum, candy, sunflower seeds, or soda on the turf. Athletes & spectators stay outside the track fence unless competing.",
      },
      {
        title: "Concessions on site",
        body: "PL Boys Track Boosters are running concessions — bring cash if you want snacks or drinks.",
      },
    ],
    whatToBring: [
      "Yinghua track uniform / team shirt",
      "Running shoes + spikes if you have them",
      "Water bottle (refillable)",
      "Snacks — meet runs into the evening",
      "Warm layers — Wednesday evening can cool off",
      "Cash for concessions (optional)",
    ],
    schedule: [
      { time: "~4:00 PM", event: "Field Events Open", detail: "Athletes plan jumps and throws around their running events.", type: "field" },
      { time: "4:15 PM", event: "Running Events Begin — Rolling Start", type: "note" },
      { time: "", event: "100m Low Hurdles", detail: "10 hurdles at lowest setting · unlimited entries", type: "track" },
      { time: "", event: "100m Dash", detail: "Unlimited entries", type: "track" },
      { time: "", event: "1600m Run", detail: "Girls first heat, boys second heat · unlimited entries", type: "track" },
      { time: "", event: "400m Dash", detail: "Unlimited entries", type: "track" },
      { time: "", event: "4x100m Relay", detail: "Multiple teams allowed", type: "track" },
      { time: "", event: "200m Dash", detail: "Unlimited entries", type: "track" },
      { time: "", event: "800m Run", detail: "Unlimited entries", type: "track" },
      { time: "", event: "Sprint Medley Relay (100-100-200-400)", detail: "Multiple teams allowed", type: "track" },
    ],
    fieldEventNotes: [
      "High Jump: Girls start at 3'6\" · Boys start at 4'0\" · 2\" progression · 3 attempts.",
      "Long Jump: 3 attempts · boys on one runway, girls on the other.",
      "Shot Put: 4 kg (women's HS weight) · 3 attempts.",
      "Discus: HS girls discus weight · 3 attempts.",
      "Max 4 events per athlete (example: 2 running + 2 field).",
      "Meet is NOT scored. Running events are hand-timed — athletes should report their time/mark to coaches.",
    ],
  },
  "2026-05-06": {
    title: "Olson MS — Bloomington Track Meet",
    date: "2026-05-06",
    dayLabel: "Wednesday, May 6",
    location: "Jefferson Athletic Center",
    address: "4001 W 102nd St, Bloomington, MN 55431",
    mapUrl: "https://maps.google.com/?q=4001+W+102nd+St+Bloomington+MN+55431",
    arrival: "Meet starts at 4:15 PM. Athletes ride the bus from Yinghua (one-way). Dismiss 3:01 · Bus 3:15.",
    transportation: "Bus from Yinghua (one-way only). Parent pickup at the meet around 6:00 PM.",
    eligibility: "Grades 6–8. 6th, 7th, and 8th boys and girls scored separately.",
    teams: "Teams attending: Lakeville, OGM, OMS, VVM, Yinghua",
    announcements: [
      {
        title: "Tell a coach which events you want to run",
        body: "Talk to Coach Drew or Coach Lily at Tuesday's pre-meet practice (5/5) and let them know which events you'd like to do.",
      },
      {
        title: "Bring your own batons",
        body: "The host school provides shot puts and discs, but each team brings their own relay batons. Coaches will have them at the meet.",
      },
      {
        title: "Max 4 events per athlete",
        body: "Each athlete may participate in NO MORE THAN four events. Examples: 3 running + 1 field, 2 running + 2 field, or 1 running + 3 field. Relays do NOT count as a running event at this meet.",
      },
    ],
    whatToBring: [
      "Yinghua track uniform / team shirt",
      "Running shoes + spikes if you have them",
      "Water bottle (refillable)",
      "Snacks — meet runs into the evening",
      "Warm layers — Wednesday evening can cool off",
      "Cash if you want concessions",
    ],
    schedule: [
      { time: "4:15 PM", event: "Meet starts — Field Events open", detail: "High Jump · Long Jump · Shot Put · Discus", type: "field" },
      { time: "", event: "Running Events (Rolling Start, in order):", type: "note" },
      { time: "", event: "110m Low Hurdles", type: "track" },
      { time: "", event: "200m Dash", type: "track" },
      { time: "", event: "1600m Run", type: "track" },
      { time: "", event: "4x100m Relay", detail: "Multiple teams allowed", type: "track" },
      { time: "", event: "400m Dash", type: "track" },
      { time: "", event: "100m Dash", type: "track" },
      { time: "", event: "800m Run", type: "track" },
      { time: "", event: "Medley Relay", detail: "100 – 100 – 200 – 400", type: "track" },
      { time: "5:45 PM", event: "All field events close", detail: "All attempts must be completed by 5:45 PM.", type: "note" },
    ],
    fieldEventNotes: [
      "High Jump: Girls start at 3'6\" with 2\" progression. Boys start at 4'0\" with 2\" progression. 3 attempts.",
      "Long Jump: 3 attempts. Boys on one runway, girls on the other.",
      "Shot Put: 7th & 8th grade boys use 4 kg. 6th grade boys and 6–8 girls use 3 kg. 3 attempts.",
      "Discus: 3 attempts. No finals — top 5 marks recorded.",
      "Set up team camps in the stadium bleachers — no playing catch in the infield.",
    ],
  },
  "2026-04-22": {
    title: "Richfield MS Meet",
    date: "2026-04-22",
    dayLabel: "Wednesday, April 22",
    location: "Richfield High School",
    address: "7001 Harriet Ave, Richfield, MN 55423",
    mapUrl: "https://maps.google.com/?q=7001+Harriet+Ave+Richfield+MN+55423",
    arrival: "Meet starts at 4:15 PM. Athletes ride the bus from Yinghua (one-way). 4 schools total — listen for event calls to keep things moving.",
    transportation: "Bus provided from Yinghua (one-way only). Parents pick up from the meet around 6:00 PM.",
    parking: "Park anywhere in the main lot at Richfield HS. The track is at the back of the property — walk over the train tracks to get there.",
    eligibility: "Grades 6–8 only — no 5th graders at this meet.",
    uniform: "Athletes can wear their jersey to school with regular uniform bottoms.",
    announcements: [
      {
        title: "Max 4 events per athlete",
        body: "Each athlete can compete in up to 4 total events (including relays): either 3 running + 1 field, OR 3 field + 1 running.",
      },
      {
        title: "Listen for event calls!",
        body: "4 schools means a lot of athletes. Stay close to the track and listen for your event being called so we can keep things moving and get out at a reasonable time.",
      },
      {
        title: "Parent pickup at the meet",
        body: "The bus ride is one-way (Yinghua → Richfield). Please plan to pick up your athlete from Richfield HS around 6:00 PM.",
      },
    ],
    signupFormUrl: "",
    signupFormEmbedUrl: "",
    whatToBring: [
      "Yinghua jersey (can wear to school with uniform bottoms)",
      "Running shoes + water bottle",
      "Warm layers — spring evenings can get chilly",
      "Snacks",
    ],
    // Running events run in this fixed order. Within each event: 6/7 girls → 8 girls → 6/7 boys → 8 boys.
    // Field events run concurrently. No per-event start times published — listen for calls at the meet.
    schedule: [
      { time: "4:15 PM", event: "Meet begins", detail: "Running events run in the order below. Within each event: 6/7 girls → 8 girls → 6/7 boys → 8 boys. Field events run concurrently throughout the meet.", type: "note" },
      { time: "", event: "Running Events (in order)", detail: "", type: "note" },
      { time: "", event: "75m Low Hurdles", detail: "7 hurdles total (13m to first, 8.5m between, 11m to finish)", type: "track" },
      { time: "", event: "100m Dash", type: "track" },
      { time: "", event: "4x200m Relay", type: "track" },
      { time: "", event: "1600m Run", detail: "One heat for all boys, one for all girls (may combine if small fields)", type: "track" },
      { time: "", event: "4x100m Relay", type: "track" },
      { time: "", event: "400m Dash", type: "track" },
      { time: "", event: "800m Run", detail: "One heat boys, one heat girls — not combined", type: "track" },
      { time: "", event: "200m Dash", type: "track" },
      { time: "", event: "4x400m Relay", detail: "Schools may enter up to 4 teams; top finish scores", type: "track" },
      { time: "", event: "Field Events (concurrent throughout meet)", detail: "", type: "note" },
      { time: "", event: "Shot Put", detail: "8 lb ball · 3 throws", type: "field" },
      { time: "", event: "Discus", detail: "3 throws", type: "field" },
      { time: "", event: "Long Jump", detail: "3 jumps", type: "field" },
      { time: "", event: "Triple Jump", detail: "3 jumps", type: "field" },
      { time: "", event: "High Jump", detail: "Starting: 7G 3'6\" · 8G 3'10\" · 7B 3'10\" · 8B 4'2\" · 2\" increases", type: "field" },
      { time: "~6:00 PM", event: "Parent Pickup", detail: "Meet wraps around 6 PM. Parents pick up at Richfield HS.", type: "note" },
    ],
  },
};

// ---- ROSTER ----
// events: array of event names (add as athletes are assigned)
const ROSTER = [
  { name: "Reuben Addington", grade: 6, events: [] },
  { name: "Brighton Balk Mmary", grade: 5, events: [] },
  { name: "Cole Beaudry", grade: 7, events: [] },
  { name: "Althea Bortel Fielder", grade: 7, events: [] },
  { name: "Keva Bowron", grade: 7, events: [] },
  { name: "Teagan Bowron", grade: 5, events: [] },
  { name: "Liam Bursell", grade: 7, events: [] },
  { name: "Mila Bursell", grade: 7, events: [] },
  { name: "Grayson Chon", grade: 7, events: [] },
  { name: "Cooper Coblentz", grade: 8, events: [] },
  { name: "Hudson Coblentz", grade: 8, events: [] },
  { name: "Nathan Coblentz", grade: 8, events: [] },
  { name: "Addis Demere", grade: 8, events: [] },
  { name: "Amen Demere", grade: 5, events: [] },
  { name: "Kai Dinger", grade: 7, events: [] },
  { name: "Alexandra Ebinger", grade: 6, events: [] },
  { name: "Cora Ebinger", grade: 8, events: [] },
  { name: "Jace Euphosin", grade: 5, events: [] },
  { name: "Elyse Folbrecht", grade: 6, events: [] },
  { name: "Walter Folbrecht", grade: 5, events: [] },
  { name: "Remy Fortin", grade: 7, events: [] },
  { name: "Gabriella Gruber", grade: 5, events: [] },
  { name: "Vienna Haas", grade: 7, events: [] },
  { name: "Aedan Herman", grade: 8, events: [] },
  { name: "Louie Herman", grade: 5, events: [] },
  { name: "Jasper Hill", grade: 5, events: [] },
  { name: "Ben Hinrichs", grade: 8, events: [] },
  { name: "Sage Houdek", grade: 8, events: [] },
  { name: "Ari Klapperich-Khuu", grade: 7, events: [] },
  { name: "Marcus Kunc", grade: 6, events: [] },
  { name: "Mattias Kunc", grade: 8, events: [] },
  { name: "Avinash Landahl", grade: 5, events: [] },
  { name: "Perrin Light-Haberstroh", grade: 6, events: [] },
  { name: "Devin Lindquist", grade: 6, events: [] },
  { name: "Gabriel Nowariak", grade: 6, events: [] },
  { name: "Annika Peterson", grade: 7, events: [] },
  { name: "Cailee Pham", grade: 8, events: [] },
  { name: "Amelia Roddy", grade: 6, events: [] },
  { name: "Audrey Roffe", grade: 7, events: [] },
  { name: "Liv Romsaas", grade: 5, events: [] },
  { name: "Frank Ryan", grade: 5, events: [] },
  { name: "Louis Ryan", grade: 7, events: [] },
  { name: "Charlotte Saeger", grade: 5, events: [] },
  { name: "Arya Sanaka", grade: 7, events: [] },
  { name: "Leo Shu", grade: 8, events: [] },
  { name: "Harper Stewart", grade: 5, events: [] },
  { name: "Ben Surla", grade: 7, events: [] },
  { name: "Otto Terhark", grade: 5, events: [] },
  { name: "Jin Trenh", grade: 8, events: [] },
  { name: "Thea Trenh", grade: 5, events: [] },
  { name: "Ethan Tschida", grade: 6, events: [] },
  { name: "Isabel Tschida", grade: 8, events: [] },
  { name: "Caleb Wilson", grade: 7, events: [] },
  { name: "Isaac Wilson", grade: 7, events: [] },
  { name: "Tiancheng Yang", grade: 5, events: [] },
  { name: "Tianming Yang", grade: 5, events: [] },
];

// ---- COACHES ----
const COACHES = [
  // Head Coaches
  { name: "Drew Addington", role: "Head Coach — Distance 800/1600, Hurdles", email: "drewadding@gmail.com" },
  { name: "Lily Ciske", role: "Head Coach — Sprints, Jumps", email: "lilian.ciske@mail.northcentral.edu" },
  // Assistant Coaches
  { name: "Angela Bortel", role: "Assistant Coach", email: "" },
  { name: "Leighton Becher", role: "Assistant Coach — Distance 800/1600", email: "" },
  // Team Manager
  { name: "Thein Sam", role: "Team Manager", email: "tnsam1@gmail.com" },
  // Parent Volunteers
  { name: "Anna Lindquist", role: "Parent Volunteer — Hurdles", email: "jasonandanna@gmail.com" },
  { name: "Charles Nowariak", role: "Parent Volunteer", email: "cdnowariak@icloud.com" },
  { name: "Kristin Petersen", role: "Parent Volunteer — Shot Put & Discus", email: "kristincpetersen@hotmail.com" },
  { name: "Anaya Mitra", role: "Parent Volunteer — Thursdays", email: "landahl.mitra@gmail.com" },
];

// ---- MEET RESULTS ----
// Add results after each meet
const RESULTS = [
  {
    date: "2026-05-09",
    meet: "St. Paul Central H.S. — All Comers Meet",
    location: "St. Paul Central High School Track",
    teamRecap: "Dragons traveled to St. Paul Central for the All Comers MS Invitational alongside TCGIS. 31 athletes competed across sprints, distance, hurdles, and field events — and nearly every Yinghua mark was a personal best!",
    resultsUrl: "https://www.athletic.net/TrackAndField/meet/654494/results/all",
    resultsUrlLabel: "Full meet results & places (athletic.net) →",
    photos: [      { src: "photos/stpaul-2026-05-09/IMG_0664.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0665.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0666.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0667.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0668.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0669.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0670.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0671.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0672.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0673.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0674.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0675.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0676.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0677.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0678.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0679.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0680.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0681.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0682.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0683.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0684.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0685.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0686.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0687.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0688.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0689.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0690.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0691.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0692.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0693.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0695.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0696.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0697.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0698.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0700.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0701.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0702.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0704.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0705.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0706.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0707.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0708.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0711.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0712.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0713.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0714.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0715.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0716.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0717.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0718.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0719.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0720.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0721.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0722.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0723.jpg" },
      { src: "photos/stpaul-2026-05-09/IMG_0725.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_145100185.MP.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_145136344.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_145137916.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_145207001.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_145241317.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_145256734.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_145257454.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_145327535.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_152142665.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_152146635.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153133627.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153134347.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153135165.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153142068.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153142304.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153142511.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153142747.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153142951.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153143133.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153544935.TS-000.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153551941.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_153602235.TS-000.MP.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_160447824.MP.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_160459575.TS-000.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_160509613.MP.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_162030542.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_162032355.MP.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_162038762.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_162047514.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_164638428.MP.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_164645484.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_164646071.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_164646306.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_164646479.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_164646855.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_164646955.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_164647647.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_164703299.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165032907.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165126457.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165129511.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165142977.MP.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165146043.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165150961.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165153390.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165157395.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165210582.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165211917.jpg" },
      { src: "photos/stpaul-2026-05-09/PXL_20260509_165436033.jpg" },
    ],
    events: [
      {
        name: "100m Dash",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Isabel Tschida", grade: 8, gender: "F", heat: "MS Girls", mark: "15.86" },
          { athlete: "Thea Trenh", grade: 5, gender: "F", heat: "MS Girls", mark: "16.70" },
          { athlete: "Teagan Bowron", grade: 5, gender: "F", heat: "MS Girls", mark: "17.46" },
          { athlete: "Gabriella Gruber", grade: 5, gender: "F", heat: "MS Girls", mark: "17.68" },
          { athlete: "Amen Demere", grade: 5, gender: "F", heat: "MS Girls", mark: "18.87" },
          { athlete: "Kai Dinger", grade: 7, gender: "M", heat: "MS Boys", mark: "13.46" },
          { athlete: "Ari Klapperich-Khuu", grade: 7, gender: "M", heat: "MS Boys", mark: "13.76" },
          { athlete: "Jin Trenh", grade: 8, gender: "M", heat: "MS Boys", mark: "14.06" },
          { athlete: "Nathan Coblentz", grade: 8, gender: "M", heat: "MS Boys", mark: "14.93" },
          { athlete: "Cooper Coblentz", grade: 8, gender: "M", heat: "MS Boys", mark: "14.97" },
          { athlete: "Leo Shu", grade: 8, gender: "M", heat: "MS Boys", mark: "15.54" },
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "MS Boys", mark: "15.54" },
          { athlete: "Isaac Wilson", grade: 7, gender: "M", heat: "MS Boys", mark: "15.58" },
          { athlete: "Arya Sanaka", grade: 7, gender: "M", heat: "MS Boys", mark: "15.76" },
          { athlete: "Remy Fortin", grade: 7, gender: "M", heat: "MS Boys", mark: "15.94" },
          { athlete: "Caleb Wilson", grade: 7, gender: "M", heat: "MS Boys", mark: "16.04" },
          { athlete: "Otto Terhark", grade: 5, gender: "M", heat: "MS Boys", mark: "16.48" },
          { athlete: "Louis Ryan", grade: 7, gender: "M", heat: "MS Boys", mark: "17.17" },
          { athlete: "Jace Euphosin", grade: 5, gender: "M", heat: "MS Boys", mark: "17.56" },
          { athlete: "Brighton Balk Mmary", grade: 5, gender: "M", heat: "MS Boys", mark: "17.57" },
          { athlete: "Ethan Tschida", grade: 6, gender: "M", heat: "MS Boys", mark: "17.88" },
        ],
      },
      {
        name: "200m Dash",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Keva Bowron", grade: 7, gender: "F", heat: "MS Girls", mark: "32.21" },
          { athlete: "Althea Bortel Fielder", grade: 7, gender: "F", heat: "MS Girls", mark: "32.86" },
          { athlete: "Isabel Tschida", grade: 8, gender: "F", heat: "MS Girls", mark: "33.33" },
          { athlete: "Kai Dinger", grade: 7, gender: "M", heat: "MS Boys", mark: "29.04" },
          { athlete: "Ari Klapperich-Khuu", grade: 7, gender: "M", heat: "MS Boys", mark: "29.13" },
          { athlete: "Jin Trenh", grade: 8, gender: "M", heat: "MS Boys", mark: "30.69" },
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "MS Boys", mark: "30.77" },
          { athlete: "Nathan Coblentz", grade: 8, gender: "M", heat: "MS Boys", mark: "30.84" },
          { athlete: "Isaac Wilson", grade: 7, gender: "M", heat: "MS Boys", mark: "33.73" },
          { athlete: "Remy Fortin", grade: 7, gender: "M", heat: "MS Boys", mark: "34.01" },
          { athlete: "Otto Terhark", grade: 5, gender: "M", heat: "MS Boys", mark: "35.17" },
          { athlete: "Louis Ryan", grade: 7, gender: "M", heat: "MS Boys", mark: "35.70" },
          { athlete: "Jace Euphosin", grade: 5, gender: "M", heat: "MS Boys", mark: "38.62" },
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "MS Boys", mark: "39.43" },
          { athlete: "Ethan Tschida", grade: 6, gender: "M", heat: "MS Boys", mark: "39.59" },
        ],
      },
      {
        name: "400m Dash",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Cooper Coblentz", grade: 8, gender: "M", heat: "MS Boys", mark: "1:06.04" },
          { athlete: "Nathan Coblentz", grade: 8, gender: "M", heat: "MS Boys", mark: "1:07.86" },
          { athlete: "Gabriel Nowariak", grade: 6, gender: "M", heat: "MS Boys", mark: "1:11.45" },
        ],
      },
      {
        name: "800m Run",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Audrey Roffe", grade: 7, gender: "F", heat: "MS Girls", mark: "2:58.47" },
          { athlete: "Amen Demere", grade: 5, gender: "F", heat: "MS Girls", mark: "3:21.86" },
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "MS Boys", mark: "3:18.50" },
          { athlete: "Grayson Chon", grade: 7, gender: "M", heat: "MS Boys", mark: "3:30.58" },
        ],
      },
      {
        name: "1600m Run",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Gabriel Nowariak", grade: 6, gender: "M", heat: "MS Boys", mark: "5:56.89" },
          { athlete: "Walter Folbrecht", grade: 5, gender: "M", heat: "MS Boys", mark: "7:46.10" },
        ],
      },
      {
        name: "100m Hurdles",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Keva Bowron", grade: 7, gender: "F", heat: "MS Girls", mark: "19.75" },
          { athlete: "Vienna Haas", grade: 7, gender: "F", heat: "MS Girls", mark: "21.24" },
          { athlete: "Teagan Bowron", grade: 5, gender: "F", heat: "MS Girls", mark: "25.00" },
          { athlete: "Ari Klapperich-Khuu", grade: 7, gender: "M", heat: "MS Boys", mark: "20.16" },
          { athlete: "Caleb Wilson", grade: 7, gender: "M", heat: "MS Boys", mark: "22.70" },
        ],
      },
      {
        name: "Shot Put",
        kind: "field",
        relay: false,
        results: [
          { athlete: "Elyse Folbrecht", grade: 6, gender: "F", heat: "MS Girls", mark: "22' 10\"" },
          { athlete: "Gabriella Gruber", grade: 5, gender: "F", heat: "MS Girls", mark: "18' 8\"" },
          { athlete: "Frank Ryan", grade: 5, gender: "M", heat: "MS Boys", mark: "17' 11\"" },
          { athlete: "Ethan Tschida", grade: 6, gender: "M", heat: "MS Boys", mark: "14' 2\"" },
          { athlete: "Brighton Balk Mmary", grade: 5, gender: "M", heat: "MS Boys", mark: "13' 7\"" },
        ],
      },
      {
        name: "Discus",
        kind: "field",
        relay: false,
        results: [
          { athlete: "Elyse Folbrecht", grade: 6, gender: "F", heat: "MS Girls", mark: "44' 0\"" },
          { athlete: "Vienna Haas", grade: 7, gender: "F", heat: "MS Girls", mark: "33' 10\"" },
          { athlete: "Leo Shu", grade: 8, gender: "M", heat: "MS Boys", mark: "60' 2\"" },
          { athlete: "Cooper Coblentz", grade: 8, gender: "M", heat: "MS Boys", mark: "59' 9\"" },
          { athlete: "Frank Ryan", grade: 5, gender: "M", heat: "MS Boys", mark: "41' 6\"" },
          { athlete: "Gabriel Nowariak", grade: 6, gender: "M", heat: "MS Boys", mark: "39' 10\"" },
          { athlete: "Walter Folbrecht", grade: 5, gender: "M", heat: "MS Boys", mark: "36' 4\"" },
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "MS Boys", mark: "29' 6\"" },
          { athlete: "Brighton Balk Mmary", grade: 5, gender: "M", heat: "MS Boys", mark: "25' 6\"" },
          { athlete: "Grayson Chon", grade: 7, gender: "M", heat: "MS Boys", mark: "24' 3\"" },
          { athlete: "Otto Terhark", grade: 5, gender: "M", heat: "MS Boys", mark: "20' 11\"" },
        ],
      },
      {
        name: "Long Jump",
        kind: "field",
        relay: false,
        results: [
          { athlete: "Isabel Tschida", grade: 8, gender: "F", heat: "MS Girls", mark: "12' 1.25\"" },
          { athlete: "Teagan Bowron", grade: 5, gender: "F", heat: "MS Girls", mark: "11' 0.5\"" },
          { athlete: "Althea Bortel Fielder", grade: 7, gender: "F", heat: "MS Girls", mark: "10' 3\"" },
          { athlete: "Audrey Roffe", grade: 7, gender: "F", heat: "MS Girls", mark: "9' 7.5\"" },
          { athlete: "Arya Sanaka", grade: 7, gender: "M", heat: "MS Boys", mark: "10' 9\"" },
          { athlete: "Remy Fortin", grade: 7, gender: "M", heat: "MS Boys", mark: "10' 0.25\"" },
          { athlete: "Ethan Tschida", grade: 6, gender: "M", heat: "MS Boys", mark: "8' 6.5\"" },
        ],
      },
    ],
  },
  {
    date: "2026-05-06",
    meet: "Olson MS — Bloomington",
    location: "Jefferson Athletic Center, Bloomington",
    teamRecap: "Dragons traveled to Jefferson HS for the Olson MS-Bloomington meet, our second meet of the season. Solid sprint, distance, hurdle, relay, and field-event performances against Lakeville, OGM, OMS, and VVM.",
    photos: [],
    events: [
      {
        name: "110m Hurdles",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Cole Beaudry", grade: 7, gender: "M", heat: "6/7 Boys", mark: "18.63" },
          { athlete: "Keva Bowron", grade: 7, gender: "F", heat: "6/7 Girls", mark: "18.68" },
          { athlete: "Vienna Haas", grade: 7, gender: "F", heat: "6/7 Girls", mark: "20.5" },
          { athlete: "Ari Klapperich-Khuu", grade: 7, gender: "M", heat: "6/7 Boys", mark: "19.0" },
        ],
      },
      {
        name: "200m Dash",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "6/7 Boys", mark: "37.89" },
          { athlete: "Althea Bortel Fielder", grade: 7, gender: "F", heat: "6/7 Girls", mark: "31.31" },
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "39.0" },
          { athlete: "Nathan Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "29.95" },
          { athlete: "Addis Demere", grade: 8, gender: "M", heat: "8 Boys", mark: "32.29" },
          { athlete: "Sage Houdek", grade: 8, gender: "F", heat: "8 Girls", mark: "34.8" },
          { athlete: "Mattias Kunc", grade: 8, gender: "M", heat: "8 Boys", mark: "31.6" },
          { athlete: "Perrin Light-Haberstroh", grade: 6, gender: "F", heat: "6/7 Girls", mark: "35.4" },
          { athlete: "Cailee Pham", grade: 8, gender: "F", heat: "8 Girls", mark: "33.1" },
          { athlete: "Jin Trenh", grade: 8, gender: "M", heat: "8 Boys", mark: "29.22" },
        ],
      },
      {
        name: "1600m Run",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Amelia Roddy", grade: 6, gender: "F", heat: "6/7 Girls", mark: "6:54" },
          { athlete: "Audrey Roffe", grade: 7, gender: "F", heat: "6/7 Girls", mark: "6:49" },
          { athlete: "Ben Surla", grade: 7, gender: "M", heat: "6/7 Boys", mark: "6:04" },
        ],
      },
      {
        name: "4x100m Relay",
        kind: "track",
        relay: true,
        results: [
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "6/7 Boys", mark: "1:04" },
          { athlete: "Cole Beaudry", grade: 7, gender: "M", heat: "6/7 Boys", mark: "57.0" },
          { athlete: "Althea Bortel Fielder", grade: 7, gender: "F", heat: "6/7 Girls", mark: "1:03" },
          { athlete: "Keva Bowron", grade: 7, gender: "F", heat: "6/7 Girls", mark: "1:03" },
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "1:00" },
          { athlete: "Nathan Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "1:04" },
          { athlete: "Addis Demere", grade: 8, gender: "M", heat: "8 Boys", mark: "1:00" },
          { athlete: "Kai Dinger", grade: 7, gender: "M", heat: "6/7 Boys", mark: "57.0" },
          { athlete: "Vienna Haas", grade: 7, gender: "F", heat: "6/7 Girls", mark: "1:03" },
          { athlete: "Ari Klapperich-Khuu", grade: 7, gender: "M", heat: "6/7 Boys", mark: "57.0" },
          { athlete: "Marcus Kunc", grade: 6, gender: "M", heat: "6/7 Boys", mark: "1:04" },
          { athlete: "Mattias Kunc", grade: 8, gender: "M", heat: "8 Boys", mark: "1:00" },
          { athlete: "Devin Lindquist", grade: 6, gender: "M", heat: "6/7 Boys", mark: "1:04" },
          { athlete: "Annika Peterson", grade: 7, gender: "F", heat: "6/7 Girls", mark: "1:03" },
          { athlete: "Jin Trenh", grade: 8, gender: "M", heat: "8 Boys", mark: "1:00" },
          { athlete: "Isaac Wilson", grade: 7, gender: "M", heat: "6/7 Boys", mark: "57.0" },
        ],
      },
      {
        name: "400m Dash",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Cooper Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "1:08" },
          { athlete: "Nathan Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "1:09.29" },
          { athlete: "Sage Houdek", grade: 8, gender: "F", heat: "8 Girls", mark: "1:17" },
          { athlete: "Devin Lindquist", grade: 6, gender: "M", heat: "6/7 Boys", mark: "1:14" },
        ],
      },
      {
        name: "100m Dash",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "6/7 Boys", mark: "17.7" },
          { athlete: "Cooper Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "14.38" },
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "14.74" },
          { athlete: "Nathan Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "13.85" },
          { athlete: "Addis Demere", grade: 8, gender: "M", heat: "8 Boys", mark: "15.7" },
          { athlete: "Kai Dinger", grade: 7, gender: "M", heat: "6/7 Boys", mark: "13.7" },
          { athlete: "Alexandra Ebinger", grade: 6, gender: "F", heat: "6/7 Girls", mark: "15.8" },
          { athlete: "Remy Fortin", grade: 7, gender: "M", heat: "6/7 Boys", mark: "16.24" },
          { athlete: "Ari Klapperich-Khuu", grade: 7, gender: "M", heat: "6/7 Boys", mark: "14.2" },
          { athlete: "Marcus Kunc", grade: 6, gender: "M", heat: "6/7 Boys", mark: "17.03" },
          { athlete: "Perrin Light-Haberstroh", grade: 6, gender: "F", heat: "6/7 Girls", mark: "15.94" },
          { athlete: "Cailee Pham", grade: 8, gender: "F", heat: "8 Girls", mark: "15.0" },
          { athlete: "Louis Ryan", grade: 7, gender: "M", heat: "6/7 Boys", mark: "16.06" },
          { athlete: "Jin Trenh", grade: 8, gender: "M", heat: "8 Boys", mark: "14.07" },
          { athlete: "Caleb Wilson", grade: 7, gender: "M", heat: "6/7 Boys", mark: "16.67" },
        ],
      },
      {
        name: "800m Run",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Cole Beaudry", grade: 7, gender: "M", heat: "6/7 Boys", mark: "2:32" },
          { athlete: "Grayson Chon", grade: 7, gender: "M", heat: "6/7 Boys", mark: "3:52" },
          { athlete: "Amelia Roddy", grade: 6, gender: "F", heat: "6/7 Girls", mark: "3:06" },
        ],
      },
      {
        name: "Medley Relay (100-100-200-400)",
        kind: "track",
        relay: true,
        results: [
          { athlete: "Cole Beaudry", grade: 7, gender: "M", heat: "6/7 Boys", mark: "2:14" },
          { athlete: "Althea Bortel Fielder", grade: 7, gender: "F", heat: "6/7 Girls", mark: "2:22.92" },
          { athlete: "Keva Bowron", grade: 7, gender: "F", heat: "6/7 Girls", mark: "2:22.92" },
          { athlete: "Kai Dinger", grade: 7, gender: "M", heat: "6/7 Boys", mark: "2:14" },
          { athlete: "Alexandra Ebinger", grade: 6, gender: "F", heat: "6/7 Girls", mark: "2:32" },
          { athlete: "Elyse Folbrecht", grade: 6, gender: "F", heat: "6/7 Girls", mark: "2:32" },
          { athlete: "Vienna Haas", grade: 7, gender: "F", heat: "6/7 Girls", mark: "2:22.92" },
          { athlete: "Ari Klapperich-Khuu", grade: 7, gender: "M", heat: "6/7 Boys", mark: "2:14" },
          { athlete: "Perrin Light-Haberstroh", grade: 6, gender: "F", heat: "6/7 Girls", mark: "2:32" },
          { athlete: "Annika Peterson", grade: 7, gender: "F", heat: "6/7 Girls", mark: "2:22.92" },
          { athlete: "Amelia Roddy", grade: 6, gender: "F", heat: "6/7 Girls", mark: "2:32" },
          { athlete: "Isaac Wilson", grade: 7, gender: "M", heat: "6/7 Boys", mark: "2:14" },
        ],
      },
      {
        name: "Shot Put",
        kind: "field",
        relay: false,
        results: [
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "6/7 Boys", mark: "15' 11\"" },
          { athlete: "Nathan Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "20' 7\"" },
          { athlete: "Elyse Folbrecht", grade: 6, gender: "F", heat: "6/7 Girls", mark: "20' 10\"" },
          { athlete: "Mattias Kunc", grade: 8, gender: "M", heat: "8 Boys", mark: "21' 6\"" },
        ],
      },
      {
        name: "Discus",
        kind: "field",
        relay: false,
        results: [
          { athlete: "Grayson Chon", grade: 7, gender: "M", heat: "6/7 Boys", mark: "22' 6.5\"" },
          { athlete: "Cooper Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "49' 9\"" },
          { athlete: "Elyse Folbrecht", grade: 6, gender: "F", heat: "6/7 Girls", mark: "36' 3\"" },
          { athlete: "Vienna Haas", grade: 7, gender: "F", heat: "6/7 Girls", mark: "44' 3\"" },
          { athlete: "Marcus Kunc", grade: 6, gender: "M", heat: "6/7 Boys", mark: "25' 11\"" },
          { athlete: "Mattias Kunc", grade: 8, gender: "M", heat: "8 Boys", mark: "49' 11\"" },
          { athlete: "Devin Lindquist", grade: 6, gender: "M", heat: "6/7 Boys", mark: "47' 4\"" },
        ],
      },
      {
        name: "Long Jump",
        kind: "field",
        relay: false,
        results: [
          { athlete: "Althea Bortel Fielder", grade: 7, gender: "F", heat: "6/7 Girls", mark: "11' 6\"" },
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "10' 0\"" },
          { athlete: "Mattias Kunc", grade: 8, gender: "M", heat: "8 Boys", mark: "11' 11\"" },
          { athlete: "Perrin Light-Haberstroh", grade: 6, gender: "F", heat: "6/7 Girls", mark: "10' 7\"" },
          { athlete: "Amelia Roddy", grade: 6, gender: "F", heat: "6/7 Girls", mark: "11' 7\"" },
          { athlete: "Audrey Roffe", grade: 7, gender: "F", heat: "6/7 Girls", mark: "11' 6\"" },
        ],
      },
    ],
  },
  {
    date: "2026-04-22",
    meet: "Richfield MS Meet",
    location: "Richfield HS",
    teamRecap: "Dragons kicked off the 2026 season at Richfield HS with 33 athletes competing against three other schools. Strong performances across sprints, hurdles, relays, distance, and throws.",
    photos: [
      { src: "photos/richfield-2026-04-22/IMG_0611.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0613.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0614.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0615.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0616.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0618.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0619.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0620.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0621.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0622.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0623.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0624.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0625.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0627.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0628.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0629.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0630.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0631.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0632.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0634.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0636.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0637.jpg" },
      { src: "photos/richfield-2026-04-22/IMG_0638.jpg" },
    ],
    events: [
      {
        name: "75m Hurdles",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Cole Beaudry", grade: 7, gender: "M", heat: "6/7 Boys", mark: "14.16" },
          { athlete: "Keva Bowron", grade: 7, gender: "F", heat: "6/7 Girls", mark: "14.42" },
          { athlete: "Vienna Haas", grade: 7, gender: "F", heat: "6/7 Girls", mark: "15.3" },
          { athlete: "Ari Klapperich-Khuu", grade: 7, gender: "M", heat: "6/7 Boys", mark: "14.3-5?" },
        ],
      },
      {
        name: "100m Dash",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "6/7 Boys", mark: "17.83" },
          { athlete: "Cooper Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "14.28" },
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "14.87" },
          { athlete: "Addis Demere", grade: 8, gender: "M", heat: "8 Boys", mark: "15.66" },
          { athlete: "Kai Dinger", grade: 7, gender: "M", heat: "6/7 Boys", mark: "14.09" },
          { athlete: "Remy Fortin", grade: 7, gender: "M", heat: "6/7 Boys", mark: "15.57" },
          { athlete: "Ben Hinrichs", grade: 8, gender: "M", heat: "8 Boys", mark: "13.49" },
          { athlete: "Ari Klapperich-Khuu", grade: 7, gender: "M", heat: "6/7 Boys", mark: "14.16" },
          { athlete: "Marcus Kunc", grade: 6, gender: "M", heat: "6/7 Boys", mark: "17.22" },
          { athlete: "Perrin Light-Haberstroh", grade: 6, gender: "F", heat: "6/7 Girls", mark: "15.94" },
          { athlete: "Devin Lindquist", grade: 6, gender: "M", heat: "6/7 Boys", mark: "15.93" },
          { athlete: "Cailee Pham", grade: 8, gender: "F", heat: "8 Girls", mark: "15.0" },
          { athlete: "Louis Ryan", grade: 7, gender: "M", heat: "6/7 Boys", mark: "16.69" },
          { athlete: "Arya Sanaka", grade: 7, gender: "F", heat: "6/7 Girls", mark: "15.34" },
          { athlete: "Jin Trenh", grade: 8, gender: "M", heat: "8 Boys", mark: "13.83" },
          { athlete: "Caleb Wilson", grade: 7, gender: "M", heat: "6/7 Boys", mark: "14.57" },
        ],
      },
      {
        name: "4x200m Relay",
        kind: "track",
        relay: true,
        results: [
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "6/7 Boys", mark: "2:22.00" },
          { athlete: "Althea Bortel Fielder", grade: 7, gender: "F", heat: "6/7 Girls", mark: "2:22.00" },
          { athlete: "Keva Bowron", grade: 7, gender: "F", heat: "6/7 Girls", mark: "2:22.00" },
          { athlete: "Vienna Haas", grade: 7, gender: "F", heat: "6/7 Girls", mark: "2:22.00" },
          { athlete: "Marcus Kunc", grade: 6, gender: "M", heat: "6/7 Boys", mark: "2:22.00" },
          { athlete: "Devin Lindquist", grade: 6, gender: "M", heat: "6/7 Boys", mark: "2:22.00" },
          { athlete: "Annika Peterson", grade: 7, gender: "F", heat: "6/7 Girls", mark: "2:22.00" },
          { athlete: "Louis Ryan", grade: 7, gender: "M", heat: "6/7 Boys", mark: "2:22.00" },
        ],
      },
      {
        name: "1600m Run",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Mattias Kunc", grade: 8, gender: "M", heat: "8 Boys", mark: "6:10.00" },
          { athlete: "Gabriel Nowariak", grade: 6, gender: "M", heat: "6/7 Boys", mark: "5:54.00" },
          { athlete: "Amelia Roddy", grade: 6, gender: "F", heat: "6/7 Girls", mark: "6:50.00" },
          { athlete: "Audrey Roffe", grade: 7, gender: "F", heat: "6/7 Girls", mark: "6:49.00" },
          { athlete: "Ben Surla", grade: 7, gender: "M", heat: "6/7 Boys", mark: "5:53.00" },
        ],
      },
      {
        name: "4x100m Relay",
        kind: "track",
        relay: true,
        results: [
          { athlete: "Cole Beaudry", grade: 7, gender: "M", heat: "6/7 Boys", mark: "58.2" },
          { athlete: "Althea Bortel Fielder", grade: 7, gender: "F", heat: "6/7 Girls", mark: "1:04.00" },
          { athlete: "Keva Bowron", grade: 7, gender: "F", heat: "6/7 Girls", mark: "1:04.00" },
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "57.0" },
          { athlete: "Addis Demere", grade: 8, gender: "M", heat: "8 Boys", mark: "57.0" },
          { athlete: "Kai Dinger", grade: 7, gender: "M", heat: "6/7 Boys", mark: "58.2" },
          { athlete: "Elyse Folbrecht", grade: 6, gender: "F", heat: "6/7 Girls", mark: "1:01.00" },
          { athlete: "Vienna Haas", grade: 7, gender: "F", heat: "6/7 Girls", mark: "1:04.00" },
          { athlete: "Ben Hinrichs", grade: 8, gender: "M", heat: "8 Boys", mark: "57.0" },
          { athlete: "Sage Houdek", grade: 8, gender: "F", heat: "8 Girls", mark: "1:01.00" },
          { athlete: "Ari Klapperich-Khuu", grade: 7, gender: "M", heat: "6/7 Boys", mark: "58.2" },
          { athlete: "Annika Peterson", grade: 7, gender: "F", heat: "6/7 Girls", mark: "1:04.00" },
          { athlete: "Cailee Pham", grade: 8, gender: "F", heat: "8 Girls", mark: "1:01.00" },
          { athlete: "Audrey Roffe", grade: 7, gender: "F", heat: "6/7 Girls", mark: "1:01.00" },
          { athlete: "Jin Trenh", grade: 8, gender: "M", heat: "8 Boys", mark: "57.0" },
          { athlete: "Isaac Wilson", grade: 7, gender: "M", heat: "6/7 Boys", mark: "58.2" },
        ],
      },
      {
        name: "400m Dash",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "6/7 Boys", mark: "1:28.00" },
          { athlete: "Cooper Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "1:09.00" },
          { athlete: "Devin Lindquist", grade: 6, gender: "M", heat: "6/7 Boys", mark: "1:18.00" },
          { athlete: "Gabriel Nowariak", grade: 6, gender: "M", heat: "6/7 Boys", mark: "1:15.00" },
        ],
      },
      {
        name: "800m Run",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Cole Beaudry", grade: 7, gender: "M", heat: "6/7 Boys", mark: "2:31.00" },
          { athlete: "Grayson Chon", grade: 7, gender: "M", heat: "6/7 Boys", mark: "3:53.00" },
          { athlete: "Amelia Roddy", grade: 6, gender: "F", heat: "6/7 Girls", mark: "3:06.00" },
          { athlete: "Ben Surla", grade: 7, gender: "M", heat: "6/7 Boys", mark: "2:43.00" },
        ],
      },
      {
        name: "200m Dash",
        kind: "track",
        relay: false,
        results: [
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "31.1" },
          { athlete: "Addis Demere", grade: 8, gender: "M", heat: "8 Boys", mark: "33.32" },
          { athlete: "Sage Houdek", grade: 8, gender: "F", heat: "8 Girls", mark: "34.16" },
          { athlete: "Perrin Light-Haberstroh", grade: 6, gender: "F", heat: "6/7 Girls", mark: "35.0" },
          { athlete: "Cailee Pham", grade: 8, gender: "F", heat: "8 Girls", mark: "31.6" },
          { athlete: "Arya Sanaka", grade: 7, gender: "F", heat: "6/7 Girls", mark: "30-31?" },
          { athlete: "Jin Trenh", grade: 8, gender: "M", heat: "8 Boys", mark: "30.42" },
          { athlete: "Isaac Wilson", grade: 7, gender: "M", heat: "6/7 Boys", mark: "32.0" },
        ],
      },
      {
        name: "4x400m Relay",
        kind: "track",
        relay: true,
        results: [
          { athlete: "Cooper Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "5:30.00" },
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "5:30.00" },
          { athlete: "Addis Demere", grade: 8, gender: "M", heat: "8 Boys", mark: "5:30.00" },
          { athlete: "Jin Trenh", grade: 8, gender: "M", heat: "8 Boys", mark: "5:30.00" },
        ],
      },
      {
        name: "Long Jump",
        kind: "field",
        relay: false,
        results: [
          { athlete: "Althea Bortel Fielder", grade: 7, gender: "F", heat: "6/7 Girls", mark: "10ft 3in" },
          { athlete: "Hudson Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "9 ft 11 in" },
          { athlete: "Remy Fortin", grade: 7, gender: "M", heat: "6/7 Boys", mark: "8ft 11in" },
          { athlete: "Sage Houdek", grade: 8, gender: "F", heat: "8 Girls", mark: "nd" },
          { athlete: "Mattias Kunc", grade: 8, gender: "M", heat: "8 Boys", mark: "12ft 5in" },
          { athlete: "Perrin Light-Haberstroh", grade: 6, gender: "F", heat: "6/7 Girls", mark: "9ft 1in" },
          { athlete: "Amelia Roddy", grade: 6, gender: "F", heat: "6/7 Girls", mark: "10ft 6in" },
          { athlete: "Audrey Roffe", grade: 7, gender: "F", heat: "6/7 Girls", mark: "9ft 8in" },
          { athlete: "Arya Sanaka", grade: 7, gender: "F", heat: "6/7 Girls", mark: "8ft 10in" },
        ],
      },
      {
        name: "Shot Put",
        kind: "field",
        relay: false,
        results: [
          { athlete: "Elyse Folbrecht", grade: 6, gender: "F", heat: "6/7 Girls", mark: "16ft 8in" },
          { athlete: "Reuben Addington", grade: 6, gender: "M", heat: "6/7 Boys", mark: "15ft 4in" },
          { athlete: "Louis Ryan", grade: 7, gender: "M", heat: "6/7 Boys", mark: "22ft 2in" },
        ],
      },
      {
        name: "Discus",
        kind: "field",
        relay: false,
        results: [
          { athlete: "Elyse Folbrecht", grade: 6, gender: "F", heat: "6/7 Girls", mark: "32ft" },
          { athlete: "Grayson Chon", grade: 7, gender: "M", heat: "6/7 Boys", mark: "27ft" },
          { athlete: "Devin Lindquist", grade: 6, gender: "M", heat: "6/7 Boys", mark: "45ft" },
          { athlete: "Cole Beaudry", grade: 7, gender: "M", heat: "6/7 Boys", mark: "38ft" },
          { athlete: "Cooper Coblentz", grade: 8, gender: "M", heat: "8 Boys", mark: "51ft" },
          { athlete: "Ben Hinrichs", grade: 8, gender: "M", heat: "8 Boys", mark: "65ft" },
          { athlete: "Mattias Kunc", grade: 8, gender: "M", heat: "8 Boys", mark: "49ft" },
          { athlete: "Vienna Haas", grade: 7, gender: "F", heat: "6/7 Girls", mark: "57ft" },
          { athlete: "Gabriel Nowariak", grade: 6, gender: "M", heat: "6/7 Boys", mark: "38ft" },
        ],
      },
    ],
  },
];

// ---- TEAM RECORDS ----
const RECORDS = [];

// ---- EXPECTATIONS ----
const EXPECTATIONS = {
  intro: "Our goal is to have a positive season where student athletes, coaches, and parents can work together to create an environment that is productive and cohesive for everyone. Students are expected to conduct themselves in a manner which follows the behavior code for Yinghua Academy. Participation in extracurricular activities is only permissible if the student is academically eligible and if the student acts in a way which is in accordance with this behavior code.",
  formLink: "",
  sections: [
    {
      title: "Practice",
      rules: [
        "I will work hard at practice and support my teammates to the best of my ability.",
        "I will show respect to my coach and teammates at all times. I am there to learn and I will not talk when the coach is talking.",
        "I will go to all practices and arrive on time. If I am late due to a teacher talking with me or a make-up test, I will arrive with a pass. If I am sick or cannot attend practice, I or my parents will contact the coach by email.",
        "I will not be \"Physical.\" Examples: kicking a basketball or volleyball, throwing a ball at someone, tripping or attempting to trip, push, poke, wrestle, spit, fight…",
        "I will not disrupt others. Examples: throwing grass, being silly, making funny noises, bringing toys or objects to practice…",
        "Before I start my practice warm up I will help put away other equipment if needed.",
      ],
      consequences: [
        "I will be given a reminder to stay on task. The coach will remind the player of the expectations.",
        "After a reminder the coach will use TAB: Take a Break One: the athlete will move away from activity and reset (re-enter practice when ready). Take a Break Two: the athlete will move away from activity and may rejoin practice only after a conversation with the coach. Take a Break Three: the athlete will move away from activity and will sit and watch the rest of the practice (parent will be emailed, called or a discussion at pick up). TAB 3 may result in loss of some game time.",
        "Repeated behavior/disruption issues: The athlete may have to sit and watch, write an apology, sit near the Athletic Director's office, game suspension or a one-week suspension (this includes at least one game).",
        "Continued behavior/disruption issues (athlete shows little to no change): the Athletic Director will work with the Student Development and Family Liaison team to come up with a solution/consequence. This could result in expulsion from the team.",
      ],
    },
    {
      title: "Meets / Games",
      rules: [
        "I will be respectful to my coach, teammates, opponents, referees and parents/fans.",
        "I will display good sportsmanship at all times.",
        "I will help clean up after the game. Example: picking up trash, picking up balls, putting away chairs…",
        "I will manage myself in the bleachers when watching my teammates. This is before a game or after a game. I must stay in the gymnasium area.",
        "Every player will treat all teammates with acceptance, respect, and friendship.",
      ],
      consequences: [
        "I will apologize to whoever has been impacted such as players, coaches, or referees.",
        "I understand that I may have reduced playing time.",
        "I understand that I may be suspended from practices or games.",
      ],
    },
    {
      title: "Academics",
      rules: [
        "I will do my best to be focused in class.",
        "I will do my homework.",
        "I will work hard to keep up with my work.",
      ],
      consequences: [
        "If I do not meet the academic expectations, I understand that this may impact my practice or playing time.",
      ],
    },
    {
      title: "Classroom Behavior",
      rules: [
        "I will be a good role model in the classroom. When appropriate or asked, I will be a leader in the classroom.",
        "I will respect my teachers and other staff.",
        "I will not distract or disrupt learning for classmates.",
      ],
      consequences: [
        "If I do not meet the classroom behavior expectations, I understand that this may impact my practice or playing time.",
      ],
    },
    {
      title: "Away Games",
      rules: [
        "I will take care of all my own belongings and trash.",
        "I will show respect to the host school.",
        "I will be a fine representative of Yinghua Academy.",
      ],
    },
    {
      title: "Bus Expectations",
      rules: [
        "No eating on the bus. I can eat my snack near the entrance to the gym.",
        "I will use a quiet voice and stay seated on the bus.",
        "I will be respectful, responsible and helpful.",
        "I will stay seated at all times.",
      ],
      consequences: [
        "If I do not meet the bus expectations, I will not be allowed to ride the bus. This can be a one time or season suspension. Should this happen, I understand that my parents will be responsible to get me to the games.",
      ],
    },
    {
      title: "Parents",
      rules: [
        "I will respect the coach, referee, players and opponents.",
        "I will cheer and be a role model of good sportsmanship.",
        "I will let the coaches coach.",
        "I will pick up my child on time from practices and games. Parents are responsible for picking up their child from away games (bus or carpool from school is a one way ride).",
      ],
    },
    {
      title: "Other Important Policies",
      rules: [
        "ABSENCE FROM SCHOOL: no practice or game that day (there are some exceptions).",
        "SCHOOL SUSPENSION OR IN-SCHOOL SUSPENSION (ISS): the student cannot participate in that day's practice or game.",
        "RULE OF 3 (3 times): Repetitive inappropriate behavior, skipping practice or other issues will result in a game(s) suspension. Skipping once or twice may lead to other consequences worked out with the coach and Athletic Director.",
        "DRUG, ALCOHOL, TOBACCO or VAPING & HARASSMENT: We will use the MN State High School Eligibility Rules as a general guideline. Infraction consequences will be adapted for the middle schooler thought process.",
      ],
    },
  ],
};

// ---- 2025 SEASON RESULTS ----
const RESULTS_2025 = {
  season: "2025",
  events: [
    {
      name: "100m Hurdles",
      results: [
        { athlete: "Ada Light-Haberstroh", mark: "14.68", meet: "Richfield Meet" },
        { athlete: "Cora Cartwright", mark: "17.1", meet: "Richfield Meet" },
        { athlete: "Saoirse Bowron", mark: "19.3", meet: "Richfield Meet" },
        { athlete: "Ari Klapperich-Khuu", mark: "19.8", meet: "Mini-meet @ Edison" },
        { athlete: "Arthur Goben", mark: "20.1", meet: "Mini-meet @ Edison" },
        { athlete: "Hazel Hill", mark: "21.2", meet: "Mini-meet @ Edison" },
        { athlete: "Orianna Gruber", mark: "21.51", meet: "Prior Lake Meet" },
        { athlete: "Santiago Guzman-Neva", mark: "22.24", meet: "Mini-meet @ Edison" },
        { athlete: "Keva Bowron", mark: "22.9", meet: "Mini-meet @ Edison" },
        { athlete: "Christopher Sabatke", mark: "23.33", meet: "Mini-meet @ Edison" },
        { athlete: "Albin Tyborski", mark: "28.8", meet: "Mini-meet @ Edison" },
        { athlete: "Althea Bortel Fielder", mark: "29.35", meet: "Mini-meet @ Edison" },
      ],
    },
    {
      name: "100m Dash",
      results: [
        { athlete: "Jonathan Trenh", mark: "12.7", meet: "Prior Lake Meet" },
        { athlete: "Sylvia Martin", mark: "13.48", meet: "Mini-meet @ Edison" },
        { athlete: "Ian Lindquist", mark: "13.55", meet: "Richfield Meet" },
        { athlete: "Owen Colai", mark: "13.8", meet: "Mini-meet @ Edison" },
        { athlete: "Arthur Goben", mark: "13.82", meet: "Richfield Meet" },
        { athlete: "Ada Light-Haberstroh", mark: "13.95", meet: "Prior Lake Meet" },
        { athlete: "Anika Robinson", mark: "14.05", meet: "Prior Lake Meet" },
        { athlete: "Albin Tyborski", mark: "14.1", meet: "Mini-meet @ Edison" },
        { athlete: "Santiago Guzman-Neva", mark: "14.13", meet: "Richfield Meet" },
        { athlete: "Nathan Coblentz", mark: "14.2", meet: "Mini-meet @ Edison" },
        { athlete: "Jin Pham", mark: "14.22", meet: "Richfield Meet" },
        { athlete: "Cooper Lindquist", mark: "14.41", meet: "Prior Lake Meet" },
        { athlete: "Addis Demere", mark: "14.6", meet: "Mini-meet @ Edison" },
        { athlete: "Orianna Gruber", mark: "14.91", meet: "Mini-meet @ Edison" },
        { athlete: "Christopher Sabatke", mark: "15.0", meet: "Richfield Meet" },
        { athlete: "Keva Bowron", mark: "15.03", meet: "Prior Lake Meet" },
        { athlete: "Cailee Pham", mark: "15.13", meet: "Richfield Meet" },
        { athlete: "Hudson Coblentz", mark: "15.21", meet: "Richfield Meet" },
        { athlete: "Althea Bortel Fielder", mark: "15.29", meet: "Richfield Meet" },
        { athlete: "Isabel Tschida", mark: "15.3", meet: "Mini-meet @ Edison" },
        { athlete: "Londyn Thomas", mark: "15.39", meet: "Prior Lake Meet" },
        { athlete: "Isaac Winkelman", mark: "15.44", meet: "Prior Lake Meet" },
        { athlete: "Ari Klapperich-Khuu", mark: "15.47", meet: "Richfield Meet" },
        { athlete: "Devin Lindquist", mark: "15.5", meet: "Mini-meet @ Edison" },
        { athlete: "Saoirse Bowron", mark: "15.8", meet: "Mini-meet @ Edison" },
        { athlete: "Hazel Hill", mark: "15.9", meet: "Prior Lake Meet" },
        { athlete: "Audrey Roffe", mark: "16.0", meet: "Richfield Meet" },
        { athlete: "Caleb Dinger", mark: "16.41", meet: "Richfield Meet" },
        { athlete: "Evelyn Evans", mark: "16.59", meet: "Mini-meet @ Edison" },
        { athlete: "Naomi Hefferan", mark: "16.6", meet: "Mini-meet @ Edison" },
        { athlete: "Perrin Light-Haberstroh", mark: "16.7", meet: "Mini-meet @ Edison" },
        { athlete: "Finley Cox", mark: "17.1", meet: "Mini-meet @ Edison" },
        { athlete: "Marcus Kunc", mark: "18.13", meet: "Mini-meet @ Edison" },
        { athlete: "Grayson Chon", mark: "18.6", meet: "Richfield Meet" },
        { athlete: "Remi Klapperich-Khuu", mark: "19.5", meet: "Mini-meet @ Edison" },
      ],
    },
    {
      name: "200m Dash",
      results: [
        { athlete: "Ian Lindquist", mark: "28.47", meet: "Richfield Meet" },
        { athlete: "Ada Light-Haberstroh", mark: "29.02", meet: "Richfield Meet" },
        { athlete: "Sylvia Martin", mark: "29.74", meet: "Mini-meet @ Edison" },
        { athlete: "Jonathan Trenh", mark: "29.9", meet: "Richfield Meet" },
        { athlete: "Nathan Coblentz", mark: "30.26", meet: "Prior Lake Meet" },
        { athlete: "Owen Colai", mark: "30.57", meet: "Mini-meet @ Edison" },
        { athlete: "Saoirse Bowron", mark: "31.7", meet: "Mini-meet @ Edison" },
        { athlete: "Jin Pham", mark: "31.94", meet: "Richfield Meet" },
        { athlete: "Hudson Coblentz", mark: "32.0", meet: "Richfield Meet" },
        { athlete: "Keva Bowron", mark: "32.36", meet: "Prior Lake Meet" },
        { athlete: "Ari Klapperich-Khuu", mark: "32.84", meet: "Prior Lake Meet" },
        { athlete: "Santiago Guzman-Neva", mark: "33.18", meet: "Richfield Meet" },
        { athlete: "Althea Bortel Fielder", mark: "33.63", meet: "Prior Lake Meet" },
        { athlete: "Addis Demere", mark: "34.4", meet: "Richfield Meet" },
        { athlete: "Londyn Thomas", mark: "34.74", meet: "Prior Lake Meet" },
        { athlete: "Audrey Roffe", mark: "36.98", meet: "Mini-meet @ Edison" },
        { athlete: "Perrin Light-Haberstroh", mark: "37.12", meet: "Mini-meet @ Edison" },
        { athlete: "Evelyn Evans", mark: "39.43", meet: "Mini-meet @ Edison" },
        { athlete: "Finley Cox", mark: "39.7", meet: "Mini-meet @ Edison" },
        { athlete: "Ethan Tschida", mark: "44.37", meet: "Mini-meet @ Edison" },
        { athlete: "Quentin Moy-Gottfried", mark: "45.8", meet: "Mini-meet @ Edison" },
        { athlete: "Greyson DeWalt", mark: "48.05", meet: "Richfield Meet" },
        { athlete: "Grayson Chon", mark: "52.2", meet: "Mini-meet @ Edison" },
      ],
    },
    {
      name: "400m Dash",
      results: [
        { athlete: "Anika Robinson", mark: "1:15", meet: "Prior Lake Meet" },
        { athlete: "Keva Bowron", mark: "1:27", meet: "Prior Lake Meet" },
        { athlete: "Greyson DeWalt", mark: "1:48", meet: "Richfield Meet" },
      ],
    },
    {
      name: "800m Run",
      results: [
        { athlete: "Sawyer Schulz", mark: "2:20", meet: "Prior Lake Meet" },
        { athlete: "Isaac Winkelman", mark: "2:49", meet: "Prior Lake Meet" },
        { athlete: "Isaac Jasper", mark: "2:58", meet: "Richfield Meet" },
        { athlete: "Rowan McGregor", mark: "2:59", meet: "Prior Lake Meet" },
        { athlete: "Cora Ebinger", mark: "3:00", meet: "Richfield Meet" },
        { athlete: "Duyen Nguyen", mark: "3:09", meet: "Mini-meet @ Edison" },
        { athlete: "Santiago Guzman-Neva", mark: "3:12", meet: "Richfield Meet" },
        { athlete: "Christopher Sabatke", mark: "3:12", meet: "Prior Lake Meet" },
        { athlete: "Alexandra Ebinger", mark: "3:16", meet: "Mini-meet @ Edison" },
        { athlete: "Amelia Roddy", mark: "3:17", meet: "Mini-meet @ Edison" },
        { athlete: "Devin Lindquist", mark: "3:18", meet: "Mini-meet @ Edison" },
        { athlete: "Hazel Courtney", mark: "4:22", meet: "Mini-meet @ Edison" },
        { athlete: "Greyson DeWalt", mark: "4:25", meet: "Prior Lake Meet" },
      ],
    },
    {
      name: "1600m Run",
      results: [
        { athlete: "Sawyer Schulz", mark: "5:12", meet: "Prior Lake Meet" },
        { athlete: "Ben Surla", mark: "6:07", meet: "Prior Lake Meet" },
        { athlete: "Isaac Jasper", mark: "6:19", meet: "Mini-meet @ Edison" },
        { athlete: "Rowan McGregor", mark: "6:29", meet: "Mini-meet @ Edison" },
        { athlete: "Mattias Kunc", mark: "6:37", meet: "Mini-meet @ Edison" },
        { athlete: "Duyen Nguyen", mark: "6:41", meet: "Mini-meet @ Edison" },
        { athlete: "Santiago Guzman-Neva", mark: "6:51", meet: "Richfield Meet" },
        { athlete: "Cora Cartwright", mark: "7:03", meet: "Prior Lake Meet" },
        { athlete: "Audrey Roffe", mark: "7:35", meet: "Prior Lake Meet" },
        { athlete: "Amelia Roddy", mark: "7:41", meet: "Mini-meet @ Edison" },
        { athlete: "Cora Ebinger", mark: "7:52", meet: "Mini-meet @ Edison" },
        { athlete: "Marcus Kunc", mark: "8:23", meet: "Mini-meet @ Edison" },
        { athlete: "Evelyn Evans", mark: "8:29", meet: "Mini-meet @ Edison" },
        { athlete: "Remi Klapperich-Khuu", mark: "9:23", meet: "Mini-meet @ Edison" },
      ],
    },
    {
      name: "4x200m Relay",
      results: [
        { athlete: "Anika, Duyen, Isaac J, Sawyer", mark: "2:03", meet: "Mini-meet @ Edison" },
        { athlete: "Addis, Nathan, Ian L, Owen", mark: "2:08", meet: "Mini-meet @ Edison" },
        { athlete: "Addis, Arthur, Hudson, Jin", mark: "2:09", meet: "Richfield Meet" },
        { athlete: "Saoirse, Sylvia, Ada, Audrey", mark: "2:10", meet: "Richfield Meet" },
        { athlete: "Ada, Orianna, Hazel H, Saoirse", mark: "2:15", meet: "Mini-meet @ Edison" },
        { athlete: "Rowan, Kai, Ben, Ari", mark: "2:19", meet: "Mini-meet @ Edison" },
        { athlete: "Cora E, Isabel, Cailee, Londyn", mark: "2:27", meet: "Mini-meet @ Edison" },
        { athlete: "Keva, Thea, Elyse, Perrin", mark: "2:28", meet: "Mini-meet @ Edison" },
        { athlete: "Reuben, Devin, Remi, Marcus", mark: "2:41", meet: "Mini-meet @ Edison" },
        { athlete: "Amelia, Quentin, Ava, Kayleigh", mark: "2:46", meet: "Mini-meet @ Edison" },
      ],
    },
    {
      name: "4x100m Relay",
      results: [
        { athlete: "Ian, Owen, Greyson, Jonathan", mark: "58.14", meet: "Richfield Meet" },
        { athlete: "Sawyer, Rowan, Chris, Isaac", mark: "59.7", meet: "Prior Lake Meet" },
        { athlete: "Grant, Addis, Cooper, Nathan", mark: "1:01", meet: "Prior Lake Meet" },
        { athlete: "Sylvia, Audrey, Cora C, Anika", mark: "1:01", meet: "Prior Lake Meet" },
        { athlete: "Saoirse, Anika, Orianna, Ada", mark: "1:01.12", meet: "Richfield Meet" },
        { athlete: "Jin, Hudson, Addis, Arthur", mark: "1:02.32", meet: "Richfield Meet" },
        { athlete: "Hazel H, Saoirse, Ada, Orianna", mark: "1:02", meet: "Prior Lake Meet" },
        { athlete: "Cailee, Londyn, Althea, Isabel", mark: "1:05.38", meet: "Richfield Meet" },
        { athlete: "Isabel, Londyn, Althea, Evelyn", mark: "1:06", meet: "Prior Lake Meet" },
        { athlete: "Isaac, Ari, Ben, Caleb", mark: "1:07", meet: "Richfield Meet" },
        { athlete: "Ari, Kai, Isaac W, Caleb", mark: "1:08", meet: "Prior Lake Meet" },
      ],
    },
    {
      name: "4x400m Relay",
      results: [
        { athlete: "Orianna, Anika, Althea, Isabel", mark: "5:24", meet: "Richfield Meet" },
      ],
    },
    {
      name: "Sprint Medley Relay",
      results: [
        { athlete: "Ada, Saoirse, Orianna, Anika", mark: "2:21", meet: "Prior Lake Meet" },
        { athlete: "Grant, Addis, Nathan, Hudson", mark: "2:22", meet: "Prior Lake Meet" },
        { athlete: "Ari, Kai, Isaac W, Ben, Caleb", mark: "2:24", meet: "Prior Lake Meet" },
        { athlete: "Althea, Keva, Isabel, Audrey", mark: "2:30", meet: "Prior Lake Meet" },
      ],
    },
    {
      name: "Long Jump",
      results: [
        { athlete: "Arthur Goben", mark: "12' 10\"", meet: "Mini-meet @ Edison" },
        { athlete: "Albin Tyborski", mark: "12' 4\"", meet: "Mini-meet @ Edison" },
        { athlete: "Owen Colai", mark: "11' 10\"", meet: "Mini-meet @ Edison" },
        { athlete: "Ada Light-Haberstroh", mark: "10' 9\"", meet: "Mini-meet @ Edison" },
        { athlete: "Alexandra Ebinger", mark: "10' 9\"", meet: "Mini-meet @ Edison" },
        { athlete: "Isabel Tschida", mark: "10' 1.5\"", meet: "Mini-meet @ Edison" },
        { athlete: "Mattias Kunc", mark: "10' 1\"", meet: "Mini-meet @ Edison" },
        { athlete: "Greyson DeWalt", mark: "10'", meet: "Mini-meet @ Edison" },
        { athlete: "Perrin Light-Haberstroh", mark: "9'", meet: "Mini-meet @ Edison" },
        { athlete: "Kayleigh Thomas", mark: "8' 10\"", meet: "Mini-meet @ Edison" },
        { athlete: "Amelia Roddy", mark: "8' 9\"", meet: "Mini-meet @ Edison" },
        { athlete: "Audrey Roffe", mark: "8' 3\"", meet: "Mini-meet @ Edison" },
        { athlete: "Ava Copperud", mark: "8' 1\"", meet: "Mini-meet @ Edison" },
        { athlete: "Evelyn Evans", mark: "7' 5.5\"", meet: "Mini-meet @ Edison" },
        { athlete: "Gabriel Nowariak", mark: "7'", meet: "Mini-meet @ Edison" },
        { athlete: "Ethan Tschida", mark: "6' 10\"", meet: "Mini-meet @ Edison" },
        { athlete: "Hazel Courtney", mark: "6' 7\"", meet: "Mini-meet @ Edison" },
      ],
    },
  ],
  // ---- IN-HOUSE MEET RESULTS ----
  inHouseMeet: {
    title: "Yinghua In-House Meet",
    teams: ["Robert", "Imagine Pope Kiwis III", "Jurassic Chickens", "Red Dead Cheetahs"],
    events: [
      {
        name: "100m Hurdles",
        results: [
          { athlete: "Albin Tyborski", team: "Jurassic Chickens", mark: "16.60", place: "1st" },
          { athlete: "Ada Light-Haberstroh", team: "Imagine Pope Kiwis III", mark: "18.08", place: "1st" },
          { athlete: "Anika Robinson", team: "Red Dead Cheetahs", mark: "18.17", place: "2nd" },
          { athlete: "Ari Klapperich-Khuu", team: "Imagine Pope Kiwis III", mark: "18.27", place: "1st" },
          { athlete: "Keva Bowron", team: "Imagine Pope Kiwis III", mark: "18.70", place: "1st" },
          { athlete: "Nathan Coblentz", team: "Robert", mark: "19.03", place: "2nd" },
          { athlete: "Orianna Gruber", team: "Robert", mark: "19.00", place: "3rd" },
          { athlete: "Cooper Coblentz", team: "Imagine Pope Kiwis III", mark: "19.05", place: "3rd" },
          { athlete: "Cora Clark", team: "Imagine Pope Kiwis III", mark: "19.07", place: "4th" },
          { athlete: "Hazel Hill", team: "Jurassic Chickens", mark: "19.17", place: "5th" },
          { athlete: "Santiago Guzman-Neva", team: "Imagine Pope Kiwis III", mark: "19.36", place: "4th" },
          { athlete: "Christopher Sabatke", team: "Imagine Pope Kiwis III", mark: "19.54", place: "5th" },
          { athlete: "Rowan McGregor", team: "Robert", mark: "20.80", place: "" },
          { athlete: "Alexandra Ebinger", team: "Red Dead Cheetahs", mark: "21.83", place: "3rd" },
          { athlete: "Evelyn Evans", team: "Robert", mark: "21.82", place: "2nd" },
          { athlete: "Perrin Light-Haberstroh", team: "Red Dead Cheetahs", mark: "21.93", place: "4th" },
          { athlete: "Mattias Kunc", team: "Red Dead Cheetahs", mark: "22.00", place: "" },
          { athlete: "Gabriel Nowariak", team: "Red Dead Cheetahs", mark: "22.50", place: "2nd" },
          { athlete: "Ava Copperud", team: "Robert", mark: "26.38", place: "5th" },
          { athlete: "Isabel Tschida", team: "Red Dead Cheetahs", mark: "26.38", place: "" },
        ],
      },
      {
        name: "100m Dash",
        results: [
          { athlete: "Jonathan Thomas", team: "Imagine Pope Kiwis III", mark: "13.41", place: "1st" },
          { athlete: "Jin Trenh", team: "Imagine Pope Kiwis III", mark: "13.56", place: "2nd" },
          { athlete: "Ian Lindquist", team: "Red Dead Cheetahs", mark: "13.61", place: "3rd" },
          { athlete: "Nathan Coblentz", team: "Robert", mark: "13.96", place: "4th" },
          { athlete: "Cooper Coblentz", team: "Imagine Pope Kiwis III", mark: "13.96", place: "5th" },
          { athlete: "Albin Tyborski", team: "Jurassic Chickens", mark: "14.40", place: "6th" },
          { athlete: "Kai Dinger", team: "Jurassic Chickens", mark: "14.48", place: "1st" },
          { athlete: "Ada Light-Haberstroh", team: "Imagine Pope Kiwis III", mark: "14.97", place: "1st" },
          { athlete: "Ari Klapperich-Khuu", team: "Imagine Pope Kiwis III", mark: "15.18", place: "2nd" },
          { athlete: "Isaac Wilson", team: "Red Dead Cheetahs", mark: "15.22", place: "3rd" },
          { athlete: "Isabel Tschida", team: "Red Dead Cheetahs", mark: "15.37", place: "2nd" },
          { athlete: "Cailee Pham", team: "Jurassic Chickens", mark: "15.37", place: "3rd" },
          { athlete: "Anika Robinson", team: "Red Dead Cheetahs", mark: "15.55", place: "4th" },
          { athlete: "Addis Demere", team: "Jurassic Chickens", mark: "15.68", place: "7th" },
          { athlete: "Devin Lindquist", team: "Jurassic Chickens", mark: "15.71", place: "4th" },
          { athlete: "Hazel Hill", team: "Jurassic Chickens", mark: "15.81", place: "5th" },
          { athlete: "Christopher Sabatke", team: "Imagine Pope Kiwis III", mark: "15.97", place: "8th" },
          { athlete: "Orianna Gruber", team: "Robert", mark: "15.98", place: "6th" },
          { athlete: "Keva Bowron", team: "Imagine Pope Kiwis III", mark: "16.00", place: "1st" },
          { athlete: "Saoirse Bowron", team: "Robert", mark: "16.59", place: "7th" },
          { athlete: "Thea Trenh", team: "Robert", mark: "16.59", place: "2nd" },
          { athlete: "Cora Clark", team: "Imagine Pope Kiwis III", mark: "16.68", place: "8th" },
          { athlete: "Alexandra Ebinger", team: "Red Dead Cheetahs", mark: "16.73", place: "3rd" },
          { athlete: "Londyn Thomas", team: "Robert", mark: "16.90", place: "9th" },
          { athlete: "Ben Surla", team: "Robert", mark: "16.98", place: "5th" },
          { athlete: "Audrey Roffe", team: "Jurassic Chickens", mark: "17.69", place: "4th" },
          { athlete: "Gabriel Nowariak", team: "Red Dead Cheetahs", mark: "17.75", place: "" },
          { athlete: "Perrin Light-Haberstroh", team: "Red Dead Cheetahs", mark: "17.87", place: "5th" },
          { athlete: "Ethan Tschida", team: "Imagine Pope Kiwis III", mark: "18.14", place: "" },
          { athlete: "Remi Klapperich-Khuu", team: "Robert", mark: "19.25", place: "" },
          { athlete: "Reuben Addington", team: "Jurassic Chickens", mark: "19.54", place: "" },
        ],
      },
      {
        name: "200m Run",
        results: [
          { athlete: "Ian Lindquist", team: "Red Dead Cheetahs", mark: "29.10", place: "1st" },
          { athlete: "Albin Tyborski", team: "Jurassic Chickens", mark: "31.03", place: "2nd" },
          { athlete: "Cooper Coblentz", team: "Imagine Pope Kiwis III", mark: "31.04", place: "3rd" },
          { athlete: "Nathan Coblentz", team: "Robert", mark: "31.19", place: "4th" },
          { athlete: "Amelia Roddy", team: "Jurassic Chickens", mark: "31.33", place: "1st" },
          { athlete: "Thea Trenh", team: "Robert", mark: "31.35", place: "2nd" },
          { athlete: "Ada Light-Haberstroh", team: "Imagine Pope Kiwis III", mark: "31.40", place: "1st" },
          { athlete: "Saoirse Bowron", team: "Robert", mark: "32.84", place: "2nd" },
          { athlete: "Santiago Guzman-Neva", team: "Imagine Pope Kiwis III", mark: "32.88", place: "5th" },
          { athlete: "Ari Klapperich-Khuu", team: "Imagine Pope Kiwis III", mark: "33.10", place: "1st" },
          { athlete: "Christopher Sabatke", team: "Imagine Pope Kiwis III", mark: "33.66", place: "6th" },
          { athlete: "Addis Demere", team: "Jurassic Chickens", mark: "34.09", place: "7th" },
          { athlete: "Grant Owens", team: "Robert", mark: "34.16", place: "8th" },
          { athlete: "Keva Bowron", team: "Imagine Pope Kiwis III", mark: "34.55", place: "3rd" },
          { athlete: "Orianna Gruber", team: "Robert", mark: "34.70", place: "3rd" },
          { athlete: "Hudson Coblentz", team: "Red Dead Cheetahs", mark: "34.76", place: "9th" },
          { athlete: "Hazel Hill", team: "Jurassic Chickens", mark: "35.13", place: "4th" },
          { athlete: "Gabriel Nowariak", team: "Red Dead Cheetahs", mark: "36.00", place: "2nd" },
          { athlete: "Isaac Wilson", team: "Red Dead Cheetahs", mark: "36.12", place: "10th" },
          { athlete: "Devin Lindquist", team: "Jurassic Chickens", mark: "36.90", place: "3rd" },
          { athlete: "Londyn Thomas", team: "Robert", mark: "36.90", place: "5th" },
          { athlete: "Audrey Roffe", team: "Jurassic Chickens", mark: "37.01", place: "4th" },
          { athlete: "Perrin Light-Haberstroh", team: "Red Dead Cheetahs", mark: "40.00", place: "5th" },
          { athlete: "Alexandra Ebinger", team: "Red Dead Cheetahs", mark: "40.46", place: "" },
          { athlete: "Evelyn Evans", team: "Robert", mark: "41.61", place: "" },
          { athlete: "Ethan Tschida", team: "Imagine Pope Kiwis III", mark: "42.13", place: "4th" },
          { athlete: "Finley Cox", team: "Jurassic Chickens", mark: "42.13", place: "" },
          { athlete: "Ava Copperud", team: "Robert", mark: "43.47", place: "" },
          { athlete: "Kayleigh Thomas", team: "Robert", mark: "43.93", place: "" },
          { athlete: "Hazel Courtney", team: "Imagine Pope Kiwis III", mark: "49.58", place: "" },
        ],
      },
      {
        name: "400m Run",
        results: [
          { athlete: "Sawyer Schulz", team: "Jurassic Chickens", mark: "", place: "1st" },
          { athlete: "Gabriel Nowariak", team: "Red Dead Cheetahs", mark: "1:24", place: "2nd" },
          { athlete: "Duyen Nguyen", team: "Imagine Pope Kiwis III", mark: "", place: "1st" },
          { athlete: "Ben Surla", team: "Robert", mark: "", place: "1st" },
          { athlete: "Cooper Coblentz", team: "Imagine Pope Kiwis III", mark: "", place: "2nd" },
          { athlete: "Isaac Jasper", team: "Robert", mark: "", place: "3rd" },
          { athlete: "Caleb Wilson", team: "Imagine Pope Kiwis III", mark: "1:31", place: "3rd" },
          { athlete: "Jasper McGregor", team: "Robert", mark: "1:37", place: "" },
          { athlete: "Audrey Roffe", team: "Jurassic Chickens", mark: "", place: "1st" },
          { athlete: "Orianna Gruber", team: "Robert", mark: "", place: "2nd" },
          { athlete: "Hazel Hill", team: "Jurassic Chickens", mark: "", place: "3rd" },
          { athlete: "Rowan McGregor", team: "Robert", mark: "", place: "4th" },
          { athlete: "Cora Clark", team: "Imagine Pope Kiwis III", mark: "", place: "4th" },
          { athlete: "Reuben Addington", team: "Jurassic Chickens", mark: "", place: "4th" },
          { athlete: "Hudson Coblentz", team: "Red Dead Cheetahs", mark: "", place: "5th" },
          { athlete: "Remi Klapperich-Khuu", team: "Robert", mark: "", place: "5th" },
        ],
      },
      {
        name: "800m Run",
        results: [
          { athlete: "Sawyer Schulz", team: "Jurassic Chickens", mark: "2:40", place: "1st" },
          { athlete: "Isaac Jasper", team: "Robert", mark: "2:46", place: "2nd" },
          { athlete: "Ben Surla", team: "Robert", mark: "2:52", place: "1st" },
          { athlete: "Duyen Nguyen", team: "Imagine Pope Kiwis III", mark: "", place: "1st" },
          { athlete: "Keva Bowron", team: "Imagine Pope Kiwis III", mark: "", place: "2nd" },
          { athlete: "Santiago Guzman-Neva", team: "Imagine Pope Kiwis III", mark: "3:26", place: "5th" },
          { athlete: "Jasper McGregor", team: "Robert", mark: "3:28", place: "2nd" },
          { athlete: "Mattias Kunc", team: "Red Dead Cheetahs", mark: "3:30", place: "" },
          { athlete: "Marcus Kunc", team: "Imagine Pope Kiwis III", mark: "3:42", place: "3rd" },
          { athlete: "Finley Cox", team: "Jurassic Chickens", mark: "3:46", place: "4th" },
          { athlete: "Ari Klapperich-Khuu", team: "Imagine Pope Kiwis III", mark: "3:48", place: "5th" },
          { athlete: "Cora Ebinger", team: "Jurassic Chickens", mark: "", place: "4th" },
          { athlete: "Evelyn Evans", team: "Robert", mark: "3:59", place: "3rd" },
          { athlete: "Amelia Roddy", team: "Jurassic Chickens", mark: "", place: "1st" },
          { athlete: "Cora Clark", team: "Imagine Pope Kiwis III", mark: "", place: "2nd" },
          { athlete: "Grayson Chon", team: "Red Dead Cheetahs", mark: "4:17", place: "" },
          { athlete: "Hazel Hill", team: "Jurassic Chickens", mark: "", place: "3rd" },
          { athlete: "Hazel Courtney", team: "Imagine Pope Kiwis III", mark: "4:24", place: "4th" },
          { athlete: "Jin Trenh", team: "Imagine Pope Kiwis III", mark: "", place: "4th" },
          { athlete: "Rowan McGregor", team: "Robert", mark: "", place: "3rd" },
        ],
      },
    ],
  },
};
